baseURL = 'http://localhost/'
languageCode = 'en-us'
title = 'Jules BOBEUF e-portfolio'
theme = 'iutdelens'
paginate = 2

[[menu.main]]
    name = "Blog"
    url = "/blog"

[[menu.main]]
    name = "Projets"
    url = "/projets"

[[menu.social]]
    name = "GitLab"
    url = "https://gitlab.univ-artois.fr/jules_bobeuf"
    pre = "<i class='fab fa-github'></i>"

[[menu.social]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/jules-bobeuf-47a683229/"
    pre = "<i class='fab fa-linkedin'></i>"

[[menu.footer]]
    name = "À propos"
    url = "/a-propos-de"

[params]
    author = "Jules B."
    authorImage = "/images/mon_avatar.jpg"


