baseURL = '/'
languageCode = 'en-us'
defaultContentLanguage = 'en'
title = 'Jules BOBEUF'
paginate = 32
disableKinds = ['taxonomy', 'term']

[languages.en]
languageName = "English"

[languages.en.params]
author = "Jules Bobeuf"
info = ["Student", "Back End Dev"]
description = "Personnal site of Jules Bobeuf"
keywords = "blog,developer,java,c#,python"

[languages.fr.params]
author = "Jules Bobeuf"
info = ["Etudiant", "Back End Dev"]
description = "Site personel de Jules Bobeuf"
keywords = "blog,developpeur,java,c#,python"


[[languages.en.menu.main]]
name = "Projects"
weight = 2
url = "/projects"

[[languages.en.menu.main]]
name = "Hangman"
weight = 4
url = "/hangman"

    [[languages.en.menu.social]]
    name = "GitHub"
    url = "https://github.com/JulesBobeuf"
    pre = "<i class='fab fa-github'></i>"
    target = "_blank"

    [[languages.en.menu.social]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/jules-bobeuf"
    pre = "<i class='fab fa-linkedin'></i>"
    target = "_blank"

    [[languages.en.menu.social]]
    name = "CV"
    pre = "CV"
    url = "/files/cv_en.pdf"
    target = "_blank"

[languages.fr]
languageName = "Français"
title = "Jules BOBEUF"

[[languages.fr.menu.main]]
name = "Projets"
weight = 2
url = "/fr/projects"

[[languages.fr.menu.main]]
name = "Jeu du Pendu"
weight = 4
url = "/fr/hangman"

    [[languages.fr.menu.social]]
    name = "GitHub"
    url = "https://github.com/JulesBobeuf"
    pre = "<i class='fab fa-github'></i>"
    target = "_blank"

    [[languages.fr.menu.social]]
    name = "Linkedin"
    url = "https://www.linkedin.com/in/jules-bobeuf"
    pre = "<i class='fab fa-linkedin'></i>"
    target = "_blank"

    [[languages.fr.menu.social]]
    name = "CV"
    pre = "CV"
    url = "/files/cv_fr.pdf"
    target = "_blank"

[params]
    author = "Jules B."
    authorImage = "/images/mon_avatar.png"


